### ISSUE TITLE
请求增加 raidrive 弹窗广告拦截

### ISSUE THREAD

**Issue by cornradio** [Alan-CRL/DesktopDrawpadBlocker#1]
![Clip_2024-07-31_18-54-17](https://github.com/user-attachments/assets/8d60c0a3-e4f5-4e9c-80fc-0e677ff0903e)

能不能自定义啊

就比如说选择一个窗体
自动把这个窗体加到黑名单里

类似火熔拦截窗口那种

**Comment by Alan-CRL** [comment]
呃，这个属于软件的插件，没有界面的。自定义的话就只能改代码。我们判断一个窗口要从他的 大小、标题、类名…… 多角度确认的，一般用户不好自定义。
